//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baidyanath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutUsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutUsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baidyanath.Resources.AboutUsResource", typeof(AboutUsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwary Family of Baidyanath Dham.
        /// </summary>
        public static string AboutFailmy {
            get {
                return ResourceManager.GetString("AboutFailmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Shree Jai Kumar&lt;/b&gt; “Pandit  Ji” was born in a Dwary Family on 7th January, 1981.The Dwary family is known as the care-taker of Keys of Baba Baidyanath temple along with all 22 temples in the premises. He is blessed with a caring parent named Shree Jawaher Charan Dwary and Smt. Purnima Devi. He lives at &lt;b&gt;Govind Khaware Lane, BaidyanathDham, Deoghar, Jharkhand, India - 814112.&lt;/b&gt;&lt;/br&gt;&lt;/br&gt;
        ///
        ///&lt;b&gt;Shree Jawaher Charan Dwary&lt;/b&gt; , is father of Shree Jai Kumar and offers Kacha Jal Puja “first worship in th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwary family is originated from Sardar panda Family “head of the temples”, bifurcated from 11th sardar panda, and got the Keys of Baba Baidyanath Temple along with all 22 temples in Temple premises; due to this we are called Dwary..
        /// </summary>
        public static string AboutUsContent2 {
            get {
                return ResourceManager.GetString("AboutUsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUsHeader {
            get {
                return ResourceManager.GetString("AboutUsHeader", resourceCulture);
            }
        }
    }
}
