//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baidyanath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactUsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactUsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baidyanath.Resources.ContactUsResource", typeof(ContactUsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;line-height: 18px; text-align: center;&quot;&gt;
        ///        &lt;u&gt;&lt;b&gt;Complete Address&lt;/b&gt;&lt;/u&gt;&lt;br /&gt;
        ///
        ///        &lt;b&gt;Shree Jai Kumar&lt;/b&gt;&lt;br /&gt;
        ///        S/O Shree Jawaher Charan Dwary&lt;br /&gt;
        ///        G S/O Late Shree Sharda Chara Dwary&lt;br /&gt;
        ///        MAA ANNAPURNA SMRITI - SARDA SADAN&lt;br /&gt;
        ///        Govind Khaware Lane&lt;br /&gt;
        ///        Baidyanath Dham, Deoghar&lt;br /&gt;
        ///        Jharkhand, India&lt;br /&gt;
        ///        &lt;b&gt;Pin-Code / Postal-Code:&lt;/b&gt; 814112&lt;br /&gt;
        ///        &lt;b&gt;Mobile No.&lt;/b&gt; +91 9204616249&lt;br /&gt;
        ///        &lt;b&gt;Mobile [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVERY PROBLEM HAS A SOLUTION WHICH COMES FROM YOUR INSIDE ONLY.
        /// </summary>
        public static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
    }
}
