//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baidyanath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baidyanath.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Baba Baidyanath&lt;/strong&gt; is one of the twelve &lt;b&gt;JYOTIRLINGAM&lt;/b&gt;  of  &lt;b&gt;lord Shiva&lt;/b&gt;. This Jyotirlingam is famous among devotees of India and other countries. The temple of Baidyanath Dham jyotirlingam is situated in Deoghar district of Santhal-Parganas area of Jharkhand state of India. Baba Baidyanath fulfill all desire of devotees, hence called as MANOKAMNA-LINGAM. Beside this Baidyanath is also known as ATMA-LINGAM, MAGESHWER-LINGAM, KAMNA-LINGAM,.
        /// </summary>
        public static string HomeContent {
            get {
                return ResourceManager.GetString("HomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAVNESHWER-BAIDYANATH, MARG- TATPURUSH, &amp; BAIJNATH.Baidyanath dham is also called as Deoghar means abode / home of Gods. &lt;/br&gt;Baidyanath dham is also well renounced in different Purans by various names like HERETIC-VAN, KETEKI-VAN etc.Being here or only by reciting the name of BABA BAIDYANATH, all wishes &amp; desires become fulfill. This jyotirlingam is brought here by demon king Ravan, hence also worshiped as RAVNESHWER BAIDYANATH.&lt;br/&gt;&lt;/br&gt;This Place of &lt;b&gt;Baba Baidyanath&lt;/b&gt; is one of the important &lt;b&gt;SIDDH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeContent2 {
            get {
                return ResourceManager.GetString("HomeContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baba Baidyanath( One of Twelve Jyotirlingam).
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A view of the Jyotirlingam..
        /// </summary>
        public static string HomePageImageCaption {
            get {
                return ResourceManager.GetString("HomePageImageCaption", resourceCulture);
            }
        }
    }
}
