//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baidyanath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TourismResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TourismResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baidyanath.Resources.TourismResource", typeof(TourismResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To reach Baba Baidyanath.
        /// </summary>
        public static string HowToReach {
            get {
                return ResourceManager.GetString("HowToReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;By Rail&lt;/b&gt; :- The nearest railway station is Baidyanath Dham (Deoghar) which is a terminal station of a 7 km branch line originating at Jasidih Jn. On the Howrah-Delhi main line. Apart from local trains on the branch line trekkers (type of jeep) taking in passengers on a per person fare basis and auto rickshaws are available. Auto-Rickshaws are available frequently just outside the Jasidih railway station. They charge Rs 8 per person in a shared auto and up to Rs 60 in a reserved auto. However, due to r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HowToReachContent {
            get {
                return ResourceManager.GetString("HowToReachContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;1. Shiv Ganga Pond: &lt;/b&gt;It is located in north of Baidyanath Dham Temple. Devotee’s take bath before worship almighty Baba Baidyanath.  &lt;p&gt;&lt;b&gt;2. Nandan Pahar / hill&lt;/b&gt; – It is located at 3 Km west from Baidyanath Dham Temple. Here a beautiful park is present for entertainment for children as wel as their parents / guardians. &lt;/p&gt;  &lt;p&gt;&lt;b&gt;3. Trikut Hill / Pahar&lt;/b&gt; – It is located 18 Km East from Baidyanath Dham Temple. It have its own Natural beauty along with Rope-Way for entertainment. &lt;/p&gt;  &lt;p&gt;&lt;b&gt;4. T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PlaceToVisitContent {
            get {
                return ResourceManager.GetString("PlaceToVisitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place to visit at deoghar.
        /// </summary>
        public static string PlaceToVisitDeoghar {
            get {
                return ResourceManager.GetString("PlaceToVisitDeoghar", resourceCulture);
            }
        }
    }
}
